language: ruby
rvm:
- 2.3.0
script: npm install -g yarn
deploy:
  provider: heroku
  api_key:
    secure: mRlp83Gutd38lMUaafJsO9dTrGdPUmDacGvUP6wIT/FsrvlNPwOgmquQIx66AcEX4lW7Sj7twhDdItTzaatz+3wn3QF/Jxet5JqnJ0xMjJDCgFVzT/t1F9GSZ/jm3OJwMgyRTjuLEttLHIbYWmbIBGXc3WPivCl5juMf1KRTb6MRSGy0YoDKEukg5eIBDGkENmy7EgSI27H6iJiTWjENf7BUuMAEMkW1Ey9JFmS469dHVmffiuk5zKPOdGLcznH4/M+/8J5QC6cMmug3l339KbjxKt3e4mvGLivfJ0LURkrue60LwzJPSY6JRPaLLm3dGDbNRzWb4HvAlrz/GL3WwKO25XRMjoBwe9Uaw+9mPngEc5k54kD1oVlz35LlWs1COrWN5BT2UjVXJXK5w5/Evh0iW0+OCeOre3nVbZGTZZyW0PtwSLO2WCMpdb6JNC/eL6bBBMgWe02IE4+oXWsflDRtS+dDH/YdkbI2pc7XvedW9sD3GgM6nEaxvg8WVmwGLZcf3Mi94lGzIMLXAbxxQv3tAQcWL7qOh8PMjDEbJqQKaP+US/waA9XcUAcSFc/KrerC6glL/GAc93h9hT3IsgJNNHmoNc+s3RWb0mNg2RzQJM/Bmww1OK1Y2oSWUkgDMvUJX1hctKgn8XPs24wO1L6o92f1LxRFThHbC6NqDsA=
  app:
    master: leonebros-staging
    production: leonebros
  on:
    repo: dben89x/leonebros-rails
  skip_cleanup: true
notifications:
  email: false
